apiVersion: v1
kind: Pod
metadata:
  name: manexample
  labels:
    appy: manex
  annotations:
    anno: "2020"
spec:
  containers:
  - name: snorer
    image: centos
    command: ["sleep", "3600"]
    env:
    - name: TZ
      value: Europe/Berlin
  restartPolicy: Never
