apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localpvc  
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Gi
