apiVersion: batch/v1
kind: Job
metadata:
  name: oknok
spec:
  backoffLimit: 10
  completions: 3
  parallelism: 1
  template:
    spec:
      containers:
      - name: oknok
        image: centos
        command: ["sh", "-c", "exit $(($(date +%s)%2))"]
      restartPolicy: Never
