apiVersion: v1
kind: Pod
metadata:
  name: secure
spec:
  containers:
  - name: snore
    image: atcomp/nwubuntu
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    env:
    - name: TZ
      value: Europe/Amsterdam
  restartPolicy: Never
