apiVersion: v1
kind: Pod
metadata:
  name: secure
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: snore
    image: atcomp/nwubuntu
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
    env:
    - name: TZ
      value: Europe/Amsterdam
  restartPolicy: Never
