#!/bin/bash

###########################################################################
# Install and activate Docker
##########################################################################
yum-config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce-20.10.11 docker-ce-cli-20.10.11 containerd.io

systemctl enable --now docker

cat <<EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF

systemctl restart docker

##########################################################################
# Disable SELinux (now and permanently)
##########################################################################
setenforce 0
sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

##########################################################################
# Disable swap (now and permanently)
##########################################################################
swapon |tail -n+2 | while read DEV REST; do swapoff "$DEV"; done
sed -i '/swap.*swap/d' /etc/fstab

##########################################################################
# Set firewall rules (now and permanently)
##########################################################################
firewall-cmd --permanent --add-port=10250/tcp
firewall-cmd --permanent --add-port=10255/tcp
firewall-cmd --permanent --add-port=30000-32767/tcp
firewall-cmd --permanent --add-port=6783/tcp
firewall-cmd  --reload
echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

##########################################################################
# Setup Kubernetes repo
##########################################################################
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=0
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg \
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

##########################################################################
# Install and activate Kubernetes
##########################################################################
yum install -y kubelet-1.23.6 kubeadm-1.23.6 kubectl-1.23.6

systemctl enable --now kubelet

##########################################################################
# Join the cluster by command 'kubeadm join ...' from
# output of command 'kubeadm init' on head node manually
##########################################################################
echo
echo =====================================================================
echo 'Manually join the cluster with the command "kubeadm join ...."'
echo =====================================================================
